# Generated by Django 5.2.13 on 2026-04-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.TextField()),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pmid', models.CharField(blank=True, max_length=50, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('paper_file', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peptide_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('peptide_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('peptide_sequence_raw', models.TextField()),
                ('peptide_backbone_clean', models.TextField(blank=True, null=True)),
                ('sequence_engineering_extracted', models.TextField(blank=True, null=True)),
                ('stereochemistry_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('peptide_modifications', models.TextField(blank=True, null=True)),
                ('sequence_length', models.IntegerField(blank=True, null=True)),
                ('has_noncanonical_residues', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['peptide_name', 'peptide_id'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('delivery_success_class', models.CharField(blank=True, max_length=100, null=True)),
                ('in_vivo_flag', models.BooleanField(blank=True, null=True)),
                ('uptake_confirmed', models.BooleanField(blank=True, null=True)),
                ('label_confidence', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('in_vitro_functional_effect', models.TextField(blank=True, null=True)),
                ('endosomal_escape_evidence', models.TextField(blank=True, null=True)),
                ('rna_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rna_payload_or_target', models.TextField(blank=True, null=True)),
                ('rna_modifications', models.TextField(blank=True, null=True)),
                ('peptide_concentration', models.CharField(blank=True, max_length=100, null=True)),
                ('rna_concentration', models.CharField(blank=True, max_length=100, null=True)),
                ('mixing_ratio', models.CharField(blank=True, max_length=100, null=True)),
                ('formulation_format', models.CharField(blank=True, max_length=255, null=True)),
                ('formulation_components', models.TextField(blank=True, null=True)),
                ('size_nm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('zeta_mv', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('model_scope', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('model_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_lines_or_primary_cells', models.TextField(blank=True, null=True)),
                ('animal_model', models.TextField(blank=True, null=True)),
                ('administration_route', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('output_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('output_value', models.TextField(blank=True, null=True)),
                ('output_units', models.CharField(blank=True, max_length=100, null=True)),
                ('output_notes', models.TextField(blank=True, null=True)),
                ('toxicity_notes', models.TextField(blank=True, null=True)),
                ('raw_row_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('curation_notes', models.TextField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.paper')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.peptide')),
            ],
            options={
                'ordering': ['experiment_id'],
            },
        ),
        migrations.CreateModel(
            name='VocabTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('raw_value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=255)),
                ('display_label', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['field_name', 'normalized_value'],
                'unique_together': {('field_name', 'raw_value')},
            },
        ),
    ]
